#               SETUP BUILD ENVIRONMENT

- name: Clone uscope docker repo
  git:
    repo: "{{github_url + '/uscope_docker.git'}}"
    dest: docker

- name: enable buildx
  shell: 
  args:
    cmd: docker buildx install
    chdir: docker

- name: create build context
  shell: 
  args:
    cmd: docker buildx create --use
    chdir: docker

#                     BUILD CONTAINERS                 

- name: Build driver container
  shell: 
  args:
    cmd: docker buildx build --ssh default -t driver:latest  -o type=docker,dest=- driver > driver.tar
    chdir: docker


- name: Build database container
  shell: 
  args:
    cmd: docker buildx build --ssh default -t database:latest  -o type=docker,dest=- database > database.tar
    chdir: docker

- name: Build server container
  shell: 
  args:
    cmd: docker buildx build --ssh default -t server:latest  -o type=docker,dest=- server > server.tar
    chdir: docker

#             BUILD PRODUCTION WEB APP ON HOST


- import_tasks: uscope_webapp_builder.yml
  vars:
    gh_url: '{{github_url}}'

- name: Load Client image
  command: 
  args: 
    cmd:  docker load --input client.tar
    chdir: docker

- name: Load Server image
  command: 
  args: 
    cmd:  docker load --input server.tar
    chdir: docker

- name: Load Database image
  command: 
  args: 
    cmd:  docker load --input database.tar
    chdir: docker
  
- name: Load Driver image
  command: 
  args: 
    cmd:  docker load --input driver.tar
    chdir: docker


#               CLEAN UP BUILD DIRECTORY

- name: Clean up docker directory
  file:
    path: docker
    state: absent

- name: Clean up webapp directory
  file:
    path: webapp
    state: absent