

########################################################
#       BUILD CONTAINERS ON HOST FOR DEPLOYMENT        #
########################################################

- hosts: localhost
  roles:
    - docker_build_devel