

- hosts: uzed
  remote_user: root
  tasks:

    - name: remove old image archive
      file:
        name: driver.tar
        state: absent
  
    - name: Remove driver container
      docker_container:
        name: root_driver_1
        state: absent

    - name: Remove driver image
      docker_image:
        state: absent
        name: driver
        tag: latest

- hosts: localhost
  roles:
    - pre_build
    - build_driver_container

- hosts: uzed
  remote_user: root
  tasks:
    - name: Load driver image
      docker_image:
        name: driver
        tag: latest
        load_path: driver.tar
        source: load