- hosts: localhost
  tasks:
    - name: create container
      docker_container:
        name: arm_server_compiler
        image: ubuntu:mantic
        command: bash
        detach: true
        interactive: true
        tty: true

    - name: add docker container to inventory
      add_host:
        name: arm_server_compiler
        ansible_connection: docker

- hosts: arm_server_compiler
  gather_facts: false
  roles:
    - arch_specific/build_server_arm

- hosts: localhost
  roles:
    - pre_build

- hosts: uzed
  remote_user: root
  tasks:
    - name: remove old image archive
      file:
        name: server.tar
        state: absent
  
    - name: Remove server container
      docker_container:
        name: root_server_testing_1
        state: absent

    - name: Remove server image
      docker_image:
        state: absent
        name: server_testing
        tag: latest

- hosts: localhost
  tasks:
    - name: copy executable to container build dir
      copy:
        src: "{{item}}"
        dest: docker/server
        mode: '0755'
      with_items:
        - fCore_cc
        - fCore_dis
        - fCore_emu
        - fCore_has
        - emulator_spec_schema.json 
        - compiler_spec_schema.json 

    - name: Clone server
      git:
        repo: https://github.com/uscope-platform/uscope_server.git
        dest: docker/server/uscope_server
      register: clone_result

    - name: Build server container
      shell: 
      args:
        cmd: docker buildx build --ssh default --platform linux/arm/v7 --build-arg SERVER_VER={{clone_result.before}} --build-arg N_CORES=12  -t server_testing:latest -o type=docker,dest=- server > server.tar
        chdir: docker
        
    - name: push server images to target
      command: 
      args:
        cmd:  scp -O server.tar root@uscope_0.local:/home/root
        chdir: docker

- hosts: localhost
  tasks:
    - name: clean up the mess
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - fCore_cc
        - fCore_dis
        - fCore_emu
        - fCore_has
        - emulator_spec_schema.json 
        - compiler_spec_schema.json 

- hosts: uzed
  remote_user: root
  tasks:
    - name: Load server image
      docker_image:
        name: server_testing
        tag: latest
        load_path: server.tar
        source: load
      vars:
        ansible_command_timeout: 240