- hosts: uzed
  remote_user: root
  tasks:

    - name: remove old image archive
      file:
        name: database.tar
        state: absent
  
    - name: Remove database container
      docker_container:
        name: root_database_testing_1
        state: absent

    - name: Remove database image
      docker_image:
        state: absent
        name: database_testing
        tag: latest

- hosts: localhost
  roles:
    - pre_build
    - role: build_database_container
      vars:
        - container_tag: database_testing:latest

- hosts: uzed
  remote_user: root
  tasks:
    - name: Load database image
      docker_image:
        name: database_testing
        tag: latest
        load_path: database.tar
        source: load