#                     BUILD CONTAINER

- name: Build database container
  shell: 
  args:
    cmd: docker buildx build --ssh default --platform linux/arm/v7 -t {{container_tag}}  -o type=docker,dest=- database > database.tar
    chdir: docker

#               PUSH CONTAINERS TO TARGET

- name: push database images to target
  command: 
  args:
    cmd:  scp -O  database.tar {{remote_host}}:/home/root
    chdir: docker
