#               SETUP BUILD ENVIRONMENT

- name: Clone uscope docker repo
  git:
    repo: "{{github_url + '/uscope_docker.git'}}"
    dest: docker
  when: clone_docker_repo | bool

#                     BUILD CONTAINER

- name: Build database container
  shell: 
  args:
    cmd: docker buildx build --ssh default --platform linux/arm/v7 -t database:latest  -o type=docker,dest=- database > database.tar
    chdir: docker

#               PUSH CONTAINERS TO TARGET

- name: push database images to target
  command: 
  args:
    cmd:  scp database.tar {{remote_host}}:/home/root
    chdir: docker

#               CLEAN UP BUILD DIRECTORY

- name: Clean up docker directory
  file:
    path: docker
    state: absent
  when: remove_docker_directory | bool