- name: Create directory for yocto toolchain
  file:
    path: "{{toolchain_target_dir}}"
    state: directory

- name: Setup directory structure with yocto and xilinx layers
  command: 
  args:
    cmd: "repo init -u git://github.com/Xilinx/yocto-manifests.git -b '{{xilinx_tools_release}}'"
    chdir: "{{toolchain_target_dir}}"

- name: Download Base repositories
  command: 
  args:
    cmd: "repo sync"
    chdir: "{{toolchain_target_dir}}"

- name: Checkout Base repositories
  command: 
  args:
    cmd: "repo start {{xilinx_tools_release}} --all"
    chdir: "{{toolchain_target_dir}}"

- name: Clone meta-uscope layer
  git:
    repo: "{{github_url+'/meta-uscope.git'}}"
    dest: "{{toolchain_target_dir+'/sources/meta-uscope'}}"
    accept_hostkey: yes

- name: Copy meta-xilinx patch
  copy:
    src: meta-xilinx.patch
    dest: "{{toolchain_target_dir+'/sources/meta-xilinx'}}"

- name: Apply microzed patch to meta-xilinx
  command:
    cmd: git apply meta-xilinx.patch
    chdir: "{{toolchain_target_dir+'/sources/meta-xilinx'}}"

- name: Remove meta-xilinx patch
  file:
    path: "{{toolchain_target_dir+'/sources/meta-xilinx/meta-xilinx.patch'}}"
    state: absent

- name: Add meta-uscope layer to bblayers
  shell: 
  args:
    cmd: "source {{toolchain_target_dir+'/setupsdk' }} && bitbake-layers add-layer {{toolchain_target_dir+'/sources/meta-uscope'}}"
    chdir: "{{toolchain_target_dir}}"
    executable: /bin/bash

- name: Copy local.conf
  copy:
    src: local.conf
    dest: "{{toolchain_target_dir+'/build/conf'}}"

- name: Copy platform XSA file
  copy:
    src: uscope_platform.xsa
    dest: "{{toolchain_target_dir+'/uscope_platform.xsa'}}"

- name: Specify paths in local conf
  replace:
    path: "{{toolchain_target_dir+'/build/conf/local.conf'}}"
    regexp: '///path///'
    replace: "{{toolchain_target_dir+'/uscope_platform.xsa'}}"
  