
- name: Create image file
  command: dd if=/dev/zero of={{image_file}} bs=1024k seek=1024 count=0

- name: Get free loopback device
  command: losetup -f
  become: yes
  register: free_loopback

- name: Attach image as loopback file
  command: losetup {{free_loopback.stdout}} {{image_file}}
  become: yes

- name: Create boot partition
  become: yes
  parted:
    device: '{{ free_loopback.stdout }}'
    number: 1
    fs_type: fat32
    flags: [ lba ]
    state: present
    part_end: 100MiB

- name: Create root partition
  become: yes
  parted:
    device: '{{ free_loopback.stdout }}'
    number: 2
    fs_type: ext4
    state: present
    part_start: 100MiB
    part_end: 100%

- name: Detach image from loopback file
  command: losetup -d {{free_loopback.stdout}}
  become: yes

- name: Attach image as loopback file with partitions
  command: losetup --partscan {{free_loopback.stdout}} {{image_file}} 
  become: yes

- name: generate partition path variables
  set_fact:
    boot_partition: "{{free_loopback.stdout+'p1'}}"
    root_partition: "{{free_loopback.stdout+'p2'}}"

- name: Create boot filesystem
  command: mkfs.fat -F 32 {{boot_partition}}
  become: yes

- name: Create boot filesystem
  command: mkfs.ext4 {{root_partition}}
  become: yes

- name: Create directory for boot partition
  file:
    path: boot_part
    state: directory

- name: Mount boot partition
  command: mount {{boot_partition}} boot_part
  become: yes

- name: Create directory for root partition
  file:
    path: root_part
    state: directory

- name: Mount root partition
  command: mount {{root_partition}} root_part
  become: yes

- name: Create boot partition directory structure
  file:
    path: boot_part/boot/extlinux
    state: directory
  become: yes

- name: Create boot script source
  copy:
    dest: boot.txt
    content: 'setenv ethaddr {{mac_address}}'
  become: yes

- name: Compile boot script
  command: mkimage -c none -A arm -T script -d boot.txt boot.scr

- name: Copy boot script
  copy:
    src: boot.scr
    dest: boot_part
  become: yes

- name: clean up boot script
  file:
    path: boot.scr
    state: absent

- name: clean up boot script
  file:
    path: boot.txt
    state: absent

- name: Copy FSBL/u-boot
  copy:
    src: "{{yocto_image_dir + 'build/tmp/deploy/images/microzed-zynq7/boot.bin'}}"
    dest: boot_part
  become: yes

- name: Copy Kenel
  copy:
    src: "{{yocto_image_dir + 'build/tmp/deploy/images/microzed-zynq7/uImage'}}"
    dest: boot_part/boot
  become: yes

- name: Copy device tree
  copy:
    src: "{{yocto_image_dir + 'build/tmp/deploy/images/microzed-zynq7/microzed-zynq7-system.dtb'}}"
    dest: boot_part/boot
  become: yes

- name: Copy extlinux
  copy:
    src: "{{yocto_image_dir + 'build/tmp/deploy/images/microzed-zynq7/extlinux.conf'}}"
    dest: boot_part/boot/extlinux
  become: yes

- name: Extract root filesystem 
  command: tar -xf {{yocto_image_dir + 'build/tmp/deploy/images/microzed-zynq7/uscope-microzed-zynq7.tar.gz'}} -C root_part
  become: yes

########################################################
#             CLEAN UP THE MESS                        #
########################################################

- name: unmount root partition
  command: umount root_part
  become: yes

- name: unmount boot partition
  command: umount boot_part
  become: yes

- name: Remove directory for boot partition
  file:
    path: boot_part
    state: absent
  become: yes

- name: Remove directory for root partition
  file:
    path: root_part
    state: absent
  become: yes

- name: Detach image from loopback file
  command: losetup -d {{free_loopback.stdout}}
  become: yes

- name: Change file ownership, group and permissions
  file:
    path: "{{image_file}}"
    owner: "{{image_user}}"
    group: "{{image_user}}"
  become: yes