- hosts: localhost
  roles:
    - build_client_container
  vars:
    - domain_name: "uscope_0.local"
    - remove_docker_directory: False
    - clone_docker_repo: True

- hosts: localhost
  roles:
    - build_driver_container
  vars:
    - domain_name: "uscope_0.local"
    - remove_docker_directory: False
    - clone_docker_repo: False

  - hosts: localhost
  roles:
    - build_database_container
  vars:
    - domain_name: "uscope_0.local"
    - remove_docker_directory: False
    - clone_docker_repo: False
    
- name: push docker-compose 
  command: 
  args:
    cmd:  scp docker-compose_zed.yml {{remote_host}}:/home/root/docker-compose.yml
    chdir: docker

  - hosts: localhost
  roles:
    - build_server_container
  vars:
    - domain_name: "uscope_0.local"
    - remove_docker_directory: True
    - clone_docker_repo: False

#               CLEAN UP BUILD DIRECTORY

- name: Clean up docker directory
  file:
    path: docker
    state: absent

- name: Clean up webapp directory
  file:
    path: webapp
    state: absent