#                     BUILD CONTAINERS                 

- name: Build driver container
  shell: 
  args:
    cmd: docker buildx build --ssh default --platform linux/arm/v7 -t {{container_tag}}  -o type=docker,dest=- driver > driver.tar
    chdir: docker

#               PUSH CONTAINERS TO TARGET

- name: push driver images to target
  command: 
  args:
    cmd:  scp -O  driver.tar {{remote_host}}:/home/root
    chdir: docker