#                     BUILD CONTAINERS                 

- name: Build driver container
  shell: 
  args:
    cmd: docker buildx build --ssh default --platform {{target_arch}} -t {{container_tag}}  -o type=docker,dest=- driver > driver.tar
    chdir: docker

#               PUSH CONTAINERS TO TARGET

- name: push driver images to target
  command: 
  args:
    cmd:  scp driver.tar {{remote_host}}:/home/petalinux
    chdir: docker