#               SETUP BUILD ENVIRONMENT

- name: Clone uscope docker repo
  git:
    repo: "{{github_url + '/uscope_docker.git'}}"
    dest: docker

- name: Build server container
  shell: 
  args:
    cmd: docker buildx build --ssh default --platform linux/arm/v7 -t server:latest  -o type=docker,dest=- server > server.tar
    chdir: docker

- name: push server images to target
  command: 
  args:
    cmd:  scp server.tar {{remote_host}}:/home/root
    chdir: docker

#               CLEAN UP BUILD DIRECTORY

- name: Clean up docker directory
  file:
    path: docker
    state: absent
  when: remove_docker_directory | bool