- name: Clone server
  git:
    repo: "{{github_url+'/uscope_server.git'}}"
    dest: docker/server/uscope_server

- name: Build server container
  shell: 
  args:
    cmd: docker buildx build --ssh default --platform linux/arm/v7 -t {{container_tag}} --build-arg N_CORES={{ansible_facts["processor_nproc"]}} -o type=docker,dest=- server > server.tar
    chdir: docker

- name: push server images to target
  command: 
  args:
    cmd: scp -O  server.tar {{remote_host}}:/home/root
    chdir: docker
     