#               SETUP BUILD ENVIRONMENT

- name: Clone uscope docker repo
  git:
    repo: "{{github_url + '/uscope_docker.git'}}"
    dest: docker

#             BUILD PRODUCTION WEB APP ON HOST
- import_tasks: uscope_webapp_builder.yml
  vars:
    app_domain_name: "{{domain_name}}"
    gh_url: '{{github_url}}'

- name: Delete server key to avoid leaks
  file:
    path: docker/client/certs/uscope_0.pem
    state: absent

- name: push client images to target
  command: 
  args:
    cmd:  scp client.tar {{remote_host}}:/home/root
    chdir: docker

#               CLEAN UP BUILD DIRECTORY

- name: Clean up docker directory
  file:
    path: docker
    state: absent
  when: remove_docker_directory | bool
  
- name: Clean up webapp directory
  file:
    path: webapp
    state: absent