#             BUILD PRODUCTION WEB APP ON HOST
- import_tasks: uscope_documentation_build.yml
  vars:
    gh_url: '{{github_url}}'

- import_tasks: uscope_webapp_builder.yml
  vars:
    app_domain_name: "{{domain_name}}"
    gh_url: '{{github_url}}'
    repo_branch: '{{git_branch}}'
    image_tag: '{{container_tag}}'
    nginx_config: '{{webserver_config}}'
    server_host: '{{domain_name}}'

- name: Delete server key to avoid leaks
  file:
    path: docker/client/certs/uscope_0.pem
    state: absent

- name: push client images to target
  command: 
  args:
    cmd:  scp -O client.tar {{remote_host}}:/home/root
    chdir: docker