---
docker_source_dir: /home/fils/git/uscope_docker
github_url: git@github.com:uscope-platform
remote_host: root@uscope_0.local
domain_name: uscope_0.local
remove_docker_directory: True
clone_docker_repo: True